package cmd

import (
	"bufio"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/bkildow/wtx/internal/config"
	"github.com/bkildow/wtx/internal/git"
	"github.com/bkildow/wtx/internal/project"
	"github.com/bkildow/wtx/internal/ui"
	"github.com/spf13/cobra"
)

// Herdr plugin identity and the environment herdr sets for plugin commands.
// See https://herdr.dev/docs/plugins/.
const (
	herdrPluginID       = "wtx"
	herdrLegacyPluginID = "wt"
	herdrMinVersion     = "0.9.0"
	herdrManifestName   = "herdr-plugin.toml"
	herdrRemoveAction   = "remove"
	herdrRemovePane     = "remove"

	herdrEventEnv    = "HERDR_PLUGIN_EVENT_JSON"
	herdrContextEnv  = "HERDR_PLUGIN_CONTEXT_JSON"
	herdrStateDirEnv = "HERDR_PLUGIN_STATE_DIR"
	herdrBinEnv      = "HERDR_BIN_PATH"

	herdrEventCreated = "worktree_created"
	herdrEventRemoved = "worktree_removed"
)

// herdrCheckout is the worktree block herdr attaches to a workspace in event
// payloads and invocation context.
type herdrCheckout struct {
	RepoKey          string `json:"repo_key"` // shared git dir, e.g. /proj/.bare or /proj/.git
	CheckoutPath     string `json:"checkout_path"`
	IsLinkedWorktree bool   `json:"is_linked_worktree"`
}

// herdrEvent is HERDR_PLUGIN_EVENT_JSON for worktree.* events; only the fields
// wtx needs are declared.
type herdrEvent struct {
	Event string `json:"event"`
	Data  struct {
		Workspace struct {
			Worktree herdrCheckout `json:"worktree"`
		} `json:"workspace"`
		Worktree struct {
			Path   string `json:"path"`
			Branch string `json:"branch"`
			IsBare bool   `json:"is_bare"`
		} `json:"worktree"`
	} `json:"data"`
}

// herdrContext is HERDR_PLUGIN_CONTEXT_JSON: the workspace focused when an
// action or plugin pane was invoked.
type herdrContext struct {
	WorkspaceID string         `json:"workspace_id"`
	Worktree    *herdrCheckout `json:"worktree"`
}

func newHerdrCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "herdr",
		Short: "Herdr integration",
		Long: `Commands for integrating wtx with herdr (https://herdr.dev).

herdr creates and deletes worktree checkouts itself. The wtx plugin reacts to
its worktree.created event to apply shared files and run setup hooks, and adds
a remove action that runs teardown hooks before herdr deletes the checkout.`,
	}

	cmd.AddCommand(newHerdrInitCmd())
	cmd.AddCommand(&cobra.Command{
		Use:    "worktree-created",
		Short:  "Handle herdr's worktree.created event",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE:   runHerdrWorktreeCreated,
	})
	cmd.AddCommand(&cobra.Command{
		Use:    "worktree-removed",
		Short:  "Handle herdr's worktree.removed event",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE:   runHerdrWorktreeRemoved,
	})
	cmd.AddCommand(&cobra.Command{
		Use:    "open-remove",
		Short:  "Open the remove pane for the focused herdr worktree",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE:   runHerdrOpenRemove,
	})
	cmd.AddCommand(&cobra.Command{
		Use:    "remove",
		Short:  "Tear down and remove the focused herdr worktree",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE:   runHerdrRemove,
	})
	return cmd
}

func newHerdrInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Install the wtx plugin into herdr",
		Long: `Writes the wtx herdr plugin manifest and links it with 'herdr plugin link'.

The plugin is global to herdr, not per project: it fires for every worktree
herdr creates or removes and does nothing for repos without a .worktree.yml.
Run it once per machine, and again after moving the wtx binary. It replaces
the plugin installed by the deprecated 'wt herdr init'.

herdr deletes a checkout before telling plugins, so teardown hooks only run
when you remove the worktree through the plugin's action. Bind it in
~/.config/herdr/config.toml:

  [[keys.command]]
  key = "prefix+shift+x"
  type = "plugin_action"
  command = "wtx.remove"
  description = "remove worktree (wtx teardown)"`,
		Args: cobra.NoArgs,
		RunE: runHerdrInit,
	}
	cmd.Flags().String("binary", "", "Path to the wtx binary herdr should run (default: this executable)")
	cmd.Flags().Bool("no-link", false, "Write the manifest but do not run 'herdr plugin link'")
	return cmd
}

// herdrManifest renders the plugin manifest. bin is the absolute wtx path
// herdr runs; herdr does not expand commands through a shell.
func herdrManifest(bin string) string {
	q := strconv.Quote
	return fmt.Sprintf(`# Generated by 'wtx herdr init'. Re-run it to update.
id = %s
name = "wtx worktrees"
version = "1"
min_herdr_version = %s
description = "Apply wtx shared files and run setup/teardown hooks for herdr worktrees"
platforms = ["macos", "linux"]

[[events]]
on = "worktree.created"
command = [%s, "herdr", "worktree-created"]

[[events]]
on = "worktree.removed"
command = [%s, "herdr", "worktree-removed"]

[[actions]]
id = %s
title = "Remove worktree (run wtx teardown)"
contexts = ["workspace"]
command = [%s, "herdr", "open-remove"]

[[panes]]
id = %s
title = "wtx remove"
placement = "overlay"
command = [%s, "herdr", "remove"]
`, q(herdrPluginID), q(herdrMinVersion), q(bin), q(bin), q(herdrRemoveAction), q(bin), q(herdrRemovePane), q(bin))
}

// herdrPluginDir is where 'wtx herdr init' writes the manifest.
func herdrPluginDir() (string, error) {
	home, err := project.WtxHome()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, "herdr-plugin"), nil
}

// legacyHerdrPluginDir is where the deprecated 'wt herdr init' wrote its
// manifest.
func legacyHerdrPluginDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "wt", "herdr-plugin"), nil
}

// herdrBinary picks the wtx path to write into the manifest: the wtx on PATH
// when it is this executable (a stable path such as a Homebrew symlink, which
// survives upgrades), else this executable.
func herdrBinary() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("cannot determine wtx binary path: %w", err)
	}
	if onPath, err := exec.LookPath("wtx"); err == nil {
		if abs, err := filepath.Abs(onPath); err == nil && sameFile(abs, exe) {
			return abs, nil
		}
	}
	return exe, nil
}

func sameFile(a, b string) bool {
	ai, err := os.Stat(a)
	if err != nil {
		return false
	}
	bi, err := os.Stat(b)
	if err != nil {
		return false
	}
	return os.SameFile(ai, bi)
}

func runHerdrInit(cmd *cobra.Command, _ []string) error {
	ctx := cmd.Context()
	dry := IsDryRun()

	bin, _ := cmd.Flags().GetString("binary")
	if bin == "" {
		var err error
		if bin, err = herdrBinary(); err != nil {
			return err
		}
	} else if abs, err := filepath.Abs(bin); err == nil {
		bin = abs
	}

	dir, err := herdrPluginDir()
	if err != nil {
		return err
	}
	manifestPath := filepath.Join(dir, herdrManifestName)

	if dry {
		ui.DryRunNotice("write " + manifestPath)
	} else {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(manifestPath, []byte(herdrManifest(bin)), 0o644); err != nil {
			return fmt.Errorf("failed to write herdr plugin manifest: %w", err)
		}
		ui.Success("Wrote " + manifestPath)
	}

	if noLink, _ := cmd.Flags().GetBool("no-link"); noLink {
		ui.Info("Link it with: herdr plugin link " + dir)
		return nil
	}

	herdrBin, err := exec.LookPath("herdr")
	if err != nil {
		ui.Warning("herdr not found in PATH; link the plugin with: herdr plugin link " + dir)
		return nil
	}

	if legacy, err := legacyHerdrPluginDir(); err == nil && generatedByWt(filepath.Join(legacy, herdrManifestName)) {
		if dry {
			ui.DryRunNotice("exec: herdr plugin unlink " + herdrLegacyPluginID)
		} else if exec.CommandContext(ctx, herdrBin, "plugin", "unlink", herdrLegacyPluginID).Run() == nil {
			ui.Success("Unlinked the legacy '" + herdrLegacyPluginID + "' herdr plugin (" + legacy + ")")
		}
	}

	if dry {
		ui.DryRunNotice("exec: herdr plugin link " + dir)
		return nil
	}

	// Relink so an existing registration picks up the new manifest.
	_ = exec.CommandContext(ctx, herdrBin, "plugin", "unlink", herdrPluginID).Run()
	link := exec.CommandContext(ctx, herdrBin, "plugin", "link", dir)
	if out, err := link.CombinedOutput(); err != nil {
		return fmt.Errorf("herdr plugin link failed: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	ui.Success("Linked herdr plugin: " + herdrPluginID)
	ui.Info("Bind the remove action so teardown hooks run before herdr deletes a checkout;")
	ui.Info("see 'wtx herdr init --help'. Plugin output: herdr plugin log list --plugin " + herdrPluginID)
	return nil
}

// generatedByWt reports whether path is a manifest written by 'wt herdr init'.
func generatedByWt(path string) bool {
	data, err := os.ReadFile(path)
	return err == nil && strings.HasPrefix(string(data), "# Generated by 'wt herdr init'")
}

// herdrProjectRoot finds the wtx Project for a herdr checkout from its
// repo_key, the shared git dir (.bare or .git inside the Project root). It
// does not walk up from the checkout: herdr puts checkouts outside the
// Project, and an ancestor's .worktree.yml must not claim an unrelated repo.
func herdrProjectRoot(repoKey string) (string, bool) {
	if repoKey == "" {
		return "", false
	}
	root := filepath.Dir(filepath.Clean(repoKey))
	return root, config.Exists(root)
}

func parseHerdrEvent(raw, want string) (herdrEvent, error) {
	var ev herdrEvent
	if raw == "" {
		return ev, fmt.Errorf("%s is not set; this command is run by herdr as a plugin event hook", herdrEventEnv)
	}
	if err := json.Unmarshal([]byte(raw), &ev); err != nil {
		return ev, fmt.Errorf("invalid %s: %w", herdrEventEnv, err)
	}
	if ev.Event != want {
		return ev, fmt.Errorf("unexpected herdr event %q (want %q)", ev.Event, want)
	}
	if ev.Data.Worktree.Path == "" {
		return ev, fmt.Errorf("herdr event is missing data.worktree.path")
	}
	return ev, nil
}

// herdrStatePath is a per-checkout file under herdr's plugin state dir. It
// lives outside the checkout because herdr deletes the checkout before the
// worktree.removed handler runs.
func herdrStatePath(kind, worktreePath string) string {
	base := os.Getenv(herdrStateDirEnv)
	if base == "" {
		base = filepath.Join(os.TempDir(), "wtx-herdr")
	}
	sum := sha256.Sum256([]byte(filepath.Clean(worktreePath)))
	name := project.WorktreeIDFromBranch(filepath.Base(worktreePath)) + "-" + hex.EncodeToString(sum[:6])
	return filepath.Join(base, kind, name)
}

func writeHerdrState(kind, worktreePath, content string) error {
	path := herdrStatePath(kind, worktreePath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// stopHerdrSetup stops a background setup that the worktree.created handler
// started for worktreePath and that is still running.
func stopHerdrSetup(worktreePath string) {
	path := herdrStatePath("setup", worktreePath)
	defer func() { _ = os.Remove(path) }()

	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil || pid <= 0 || pid == os.Getpid() || !project.IsProcessAlive(pid) {
		return
	}
	ui.Warning(fmt.Sprintf("Stopping in-progress setup (PID %d)", pid))
	stopProcess(pid)
}

func runHerdrWorktreeCreated(cmd *cobra.Command, _ []string) error {
	ctx := cmd.Context()
	ev, err := parseHerdrEvent(os.Getenv(herdrEventEnv), herdrEventCreated)
	if err != nil {
		return err
	}
	root, ok := herdrProjectRoot(ev.Data.Workspace.Worktree.RepoKey)
	if !ok || ev.Data.Worktree.IsBare {
		return nil // not a wtx project: herdr's plugin is global
	}

	clone, err := project.OpenAt(ctx, root, project.Options{BatchMode: true})
	if err != nil {
		return err
	}
	cfg := clone.Config()
	worktreePath, branch := ev.Data.Worktree.Path, ev.Data.Worktree.Branch

	// herdr runs a plain 'git worktree add', which leaves a checkout of a bare
	// repository unusable; finish it the way 'wtx add' does.
	if clone.Layout() == project.BareLayout {
		runner := clone.Runner()
		if err := runner.EnableWorktreeConfig(ctx); err != nil {
			return err
		}
		if err := runner.SetWorktreeBareFalse(ctx, worktreePath); err != nil {
			return err
		}
	}

	if err := project.EnsureGitExclude(clone.GitDir(), false); err != nil {
		ui.Warning("Could not configure git excludes: " + err.Error())
	}

	vars := project.NewTemplateVars(root, worktreePath, branch)
	result, err := project.Apply(root, worktreePath, cfg, false, &vars, resolveIncludeSource(ctx, clone))
	if err != nil {
		return err
	}
	msg := fmt.Sprintf("Prepared herdr worktree %s (%d included, %d copied, %d symlinked)",
		branch, result.Included, result.Copied, result.Symlinked)

	if len(cfg.Setup) == 0 && len(cfg.ParallelSetup) == 0 {
		ui.Success(msg)
		return nil
	}

	// Run setup the way 'wtx add --background' does, so 'wtx status' and
	// 'wtx logs' work for herdr checkouts, and remember its PID outside the
	// checkout in case herdr deletes the checkout while setup still runs.
	if err := runSetupBackground(root, worktreePath, branch, cfg, false, msg); err != nil {
		return err
	}
	if state, err := project.ReadSetupState(worktreePath); err == nil && state != nil && state.PID > 0 {
		if err := writeHerdrState("setup", worktreePath, strconv.Itoa(state.PID)); err != nil {
			ui.Warning("Could not record setup PID: " + err.Error())
		}
	}
	return nil
}

func runHerdrWorktreeRemoved(_ *cobra.Command, _ []string) error {
	ev, err := parseHerdrEvent(os.Getenv(herdrEventEnv), herdrEventRemoved)
	if err != nil {
		return err
	}
	root, ok := herdrProjectRoot(ev.Data.Workspace.Worktree.RepoKey)
	if !ok || ev.Data.Worktree.IsBare {
		return nil
	}
	worktreePath, branch := ev.Data.Worktree.Path, ev.Data.Worktree.Branch

	stopHerdrSetup(worktreePath)

	marker := herdrStatePath("removed", worktreePath)
	if _, err := os.Stat(marker); err == nil {
		_ = os.Remove(marker)
		ui.Success("Removed herdr worktree " + branch + " (teardown ran first)")
		return nil
	}

	cfg, err := config.Load(root)
	if err != nil {
		return err
	}
	skipped := append(append([]string{}, cfg.Teardown...), cfg.ParallelTeardown...)
	if len(skipped) == 0 {
		return nil
	}

	// herdr deleted the checkout before emitting the event, and teardown
	// hooks run inside it, so they cannot run now.
	ui.Warning(fmt.Sprintf("herdr removed %s before wtx could run teardown; skipped %d hook(s):", branch, len(skipped)))
	for _, h := range skipped {
		ui.Info("  " + h)
	}
	ui.Info("Remove worktrees with the wtx.remove action instead; see 'wtx herdr init --help'.")
	notifyHerdr("wtx: teardown skipped for "+branch,
		fmt.Sprintf("%d teardown hook(s) did not run. Use the wtx.remove action to remove wtx worktrees.", len(skipped)))
	return nil
}

// notifyHerdr shows a herdr notification. Plugin event output only reaches
// 'herdr plugin log', which nobody watches.
func notifyHerdr(title, body string) {
	_ = exec.Command(herdrBin(), "notification", "show", title, "--body", body).Run()
}

func herdrBin() string {
	if bin := os.Getenv(herdrBinEnv); bin != "" {
		return bin
	}
	return "herdr"
}

func loadHerdrContext() (herdrContext, error) {
	var hc herdrContext
	raw := os.Getenv(herdrContextEnv)
	if raw == "" {
		return hc, fmt.Errorf("%s is not set; this command is run by the wtx herdr plugin", herdrContextEnv)
	}
	if err := json.Unmarshal([]byte(raw), &hc); err != nil {
		return hc, fmt.Errorf("invalid %s: %w", herdrContextEnv, err)
	}
	return hc, nil
}

// runHerdrOpenRemove is the remove action. Actions run without a terminal, so
// it opens the remove pane, which has one, over the focused workspace.
func runHerdrOpenRemove(cmd *cobra.Command, _ []string) error {
	hc, err := loadHerdrContext()
	if err != nil {
		return err
	}
	args := []string{"plugin", "pane", "open", "--plugin", herdrPluginID, "--entrypoint", herdrRemovePane, "--focus"}
	if hc.WorkspaceID != "" {
		args = append(args, "--workspace", hc.WorkspaceID)
	}
	out, err := exec.CommandContext(cmd.Context(), herdrBin(), args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("herdr plugin pane open failed: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// runHerdrRemove runs in the remove pane. Errors stay on screen until the
// user presses Enter; on success herdr closes the workspace, pane included.
func runHerdrRemove(cmd *cobra.Command, _ []string) error {
	if err := herdrRemove(cmd.Context(), &ui.InteractivePrompter{}); err != nil {
		if ui.IsUserAbort(err) {
			return nil
		}
		ui.Error(err.Error())
		waitForEnter()
	}
	return nil
}

func waitForEnter() {
	_, _ = fmt.Fprint(ui.Output, "\nPress Enter to close.")
	_, _ = bufio.NewReader(os.Stdin).ReadString('\n')
}

func herdrRemove(ctx context.Context, prompter ui.Prompter) error {
	hc, err := loadHerdrContext()
	if err != nil {
		return err
	}
	if hc.Worktree == nil || !hc.Worktree.IsLinkedWorktree || hc.WorkspaceID == "" {
		return fmt.Errorf("the focused herdr workspace is not a worktree checkout")
	}
	root, ok := herdrProjectRoot(hc.Worktree.RepoKey)
	if !ok {
		return fmt.Errorf("%s is not in a wtx project; use herdr's 'Delete worktree checkout' instead", hc.Worktree.CheckoutPath)
	}

	clone, err := project.OpenAt(ctx, root, project.Options{DryRun: IsDryRun()})
	if err != nil {
		return err
	}
	wts, err := clone.Worktrees(ctx)
	if err != nil {
		return err
	}
	wt, ok := findWorktreeByPath(wts.Managed, hc.Worktree.CheckoutPath)
	if !ok {
		return fmt.Errorf("%s is not a worktree of %s", hc.Worktree.CheckoutPath, root)
	}

	force := false
	dirty, err := clone.Runner().IsWorktreeDirty(ctx, wt.Path)
	if err != nil {
		return err
	}
	if dirty {
		confirmed, err := prompter.Confirm(wt.Branch + " has uncommitted changes. Remove it anyway?")
		if err != nil {
			return err
		}
		if !confirmed {
			ui.Info("Cancelled.")
			return nil
		}
		force = true
	}

	terminateBackgroundSetup(wt.Path, wt.Branch, IsDryRun())
	stopHerdrSetup(wt.Path)

	cfg := clone.Config()
	env := clone.ProjectEnv(project.NewTemplateVars(root, wt.Path, wt.Branch), wts)
	if err := project.RunTeardownHooks(ctx, cfg, env, IsDryRun()); err != nil {
		ui.Warning("Teardown hooks failed: " + err.Error())
	}
	if err := project.RunParallelTeardownHooks(ctx, cfg, env, IsDryRun()); err != nil {
		ui.Warning("Parallel teardown hooks failed: " + err.Error())
	}

	args := []string{"worktree", "remove", "--workspace", hc.WorkspaceID}
	if force {
		args = append(args, "--force")
	}
	if IsDryRun() {
		ui.DryRunNotice("exec: herdr " + strings.Join(args, " "))
		waitForEnter()
		return nil
	}

	// herdr deletes the checkout, closes the workspace (and this pane with
	// it), and emits worktree.removed; the marker tells that handler teardown
	// already ran.
	if err := writeHerdrState("removed", wt.Path, wt.Branch); err != nil {
		ui.Warning("Could not record teardown: " + err.Error())
	}
	ui.Step("Removing worktree: " + wt.Branch)
	if out, err := exec.CommandContext(ctx, herdrBin(), args...).CombinedOutput(); err != nil {
		_ = os.Remove(herdrStatePath("removed", wt.Path))
		return fmt.Errorf("teardown ran, but herdr worktree remove failed: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// findWorktreeByPath returns the worktree checked out at path, comparing
// canonical paths so /tmp and /private/tmp match.
func findWorktreeByPath(worktrees []git.WorktreeInfo, path string) (git.WorktreeInfo, bool) {
	want := ui.CanonicalPath(path)
	for _, wt := range worktrees {
		if ui.CanonicalPath(wt.Path) == want {
			return wt, true
		}
	}
	return git.WorktreeInfo{}, false
}
